name: Zachary Zimbler
bio: 'Developer, Adventurer, Music Lover'
picture: 'assets/images/profile.jpg'

#url: http://zzimbler.com
url: 
permalink: /:title/

twitter: zzimbler
instagram: zzimbler
linkedin: zzimbler
github: zzimbler
email: zachzimbler@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need projects, comment the *projects* configs below
projects: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
